namespace LowLevelSystems.CharacterSystems.Components.PropertySystems
{
public enum PropertyEnum
{
    None,
    MaxHP,
    MaxBodyVeinHp,
    MaxSpiritVeinHp,
    MaxAp,
    TimesToRecoverToMaxAp,
    Speed,
    MinAttack,
    MaxAttack,
    BodyVeinResistance,
    SpiritVeinResistance,
    CriticalRate,
    CriticalResistance,
    CriticalDamage,
    DodgeRate,
    HitRate,
    ControlResistance,
    DamageResistance,
    DeBuffResistance,
    
    Health = 201,
    Balance,
    Strength,
    Agility,
    Dexterity,
    Precision,
    Toughness = 207,
    
    Persuade = 301,
    Induce,
    Threat,
    Cheat,
    Music,
    Chess,
    Calligraphy,
    Painting,
    Cooking,
    Medical,
    Smelt,
    Forging,
    Trade,
    Steal,
    Calculate,
    Charm,
    
    P1 = 401,
    P2,
    P3,
    P4,
    P5,
}
}